# Generated by Django 4.1.4 on 2023-01-20 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
