# Generated by Django 4.1.4 on 2023-01-07 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_order_deliveredat_alter_order_paidat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='ShippingPrice',
            new_name='shippingPrice',
        ),
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
